name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          IMAGE_NAME=mohdjami/koinx-assignment
          TIMESTAMP_TAG=${IMAGE_NAME}:$(date +%s)
          docker build . --file Dockerfile --tag ${IMAGE_NAME}:latest --tag $TIMESTAMP_TAG
          
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=mohdjami/koinx-assignment
          docker push ${IMAGE_NAME}:latest
          docker push $TIMESTAMP_TAG
