name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define Image Name and Tags
        run: |
          echo "IMAGE_NAME=mohdjami/koinx-assignment" >> $GITHUB_ENV
          echo "TIMESTAMP_TAG=${{ env.IMAGE_NAME }}:$(date +%s)" >> $GITHUB_ENV
          echo "LATEST_TAG=${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.LATEST_TAG }} --tag ${{ env.TIMESTAMP_TAG }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.LATEST_TAG }}
          docker push ${{ env.TIMESTAMP_TAG }}
